--liquibase formatted sql

--changeset chern:2025-03-01-schema
CREATE SCHEMA IF NOT EXISTS bookstore;

--changeset chern:2025-03-01-authors
CREATE TABLE authors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(155),
    last_name VARCHAR(255),
    middle_name VARCHAR(100),
    description TEXT
);

--changeset chern:2025-03-01-genres
CREATE TABLE genres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description TEXT
);

--changeset chern:2025-03-01-books
CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    author_id BIGINT REFERENCES authors (id) ON DELETE CASCADE,
    description TEXT,
    serial_number VARCHAR(50),
    isbn VARCHAR(20)
);

--changeset chern:2025-03-01-books-genres
CREATE TABLE books_genres (
    book_id BIGINT REFERENCES books(id) ON DELETE CASCADE,
    genre_id BIGINT REFERENCES genres(id) ON DELETE CASCADE,
    PRIMARY KEY (book_id, genre_id)
);

--changeset chern:2025-03-01-comments
CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT REFERENCES books(id) ON DELETE CASCADE,
    text VARCHAR(255),
    created DATE,
    author VARCHAR(255)
);
