server:
  port: 9090
spring:
  datasource:
    schema: bookstore
    #    url: jdbc:h2:mem:maindb;MODE=MSSQLServer;INIT=CREATE SCHEMA IF NOT EXISTS BOOKSTORE;
#    url: jdbc:h2:file:./_data/jpa-demo;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS BOOKSTORE;
    url: jdbc:postgresql://localhost:5477/bookstore;
    hikari:
      schema: bookstore
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    liquibase-schema: "public"
    default-schema: "bookstore"
  docker:
    compose:
      lifecycle-management: start_only
      file: "docker-compose.yaml"
  shell:
    interactive:
      enabled: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: bookstore-client
            client-secret: bookstore-client-secret
            authorization-grant-type: authorization_code
            redirect-uri: "${KEYCLOAK_BASE_URL:http://localhost:9090}/login/oauth2/code/keycloak"
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: "${KEYCLOAK_BASE_URL:http://localhost:58080}/realms/bookstore"
            authorization-uri: "${KEYCLOAK_BASE_URL:http://localhost:58080}/realms/bookstore/protocol/openid-connect/auth"
            token-uri: "${KEYCLOAK_BASE_URL:http://localhost:58080}/realms/bookstore/protocol/openid-connect/token"
      resourceserver:
        jwt:
          issuer-uri: "${KEYCLOAK_BASE_URL:http://localhost:58080}/realms/bookstore"
          jwk-set-uri: "${KEYCLOAK_BASE_URL:http://localhost:58080}/realms/bookstore/protocol/openid-connect/certs"
logging:
  level:
    root: "debug"
    org.hibernate: "debug"
    liquibase: "debug"

springdoc:
  show-oauth2-endpoints: true
  show-actuator: true
  show-login-endpoint: true
  swagger-ui:
    disable-swagger-default-url: true
    try-it-out-enabled: true
