services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    restart: always
    ports:
      - "8443:8443"
      - "58080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_DB_URL: jdbc:postgresql://keycloak_postgres:5432/keycloak
      KC_DB: postgres
      KC_DB_USERNAME: ${KC_POSTGRES_USER}
      KC_DB_PASSWORD: ${KC_POSTGRES_PASSWORD}
#      KEYCLOAK_IMPORT: "/opt/keycloak/data/import/bookstore-realm.json"
    depends_on:
      - keycloak_postgres
    networks:
      - keycloak-network
    command:
      - "start-dev"
      - "--import-realm"
      - "-features=scripts"
    volumes:
#      - ./_keycloak:/opt/keycloak/data/import
      - ./import/bookstore-realm.json:/opt/keycloak/data/import/bookstore-realm.json
    labels:
      org.springframework.boot.readiness-check.tcp.disable: true
  keycloak_postgres:
    container_name: keycloak_postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KC_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KC_POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432
    labels:
      org.springframework.boot.ignore: true
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

networks:
  keycloak-network:
    name: keycloak-network

volumes:
  postgres_data: