--liquibase formatted sql

--changeset chern:2025-03-22-bookstore_management
CREATE SCHEMA bookstore_management;

--liquibase formatted sql
--changeset chern:2025-03-22-authorities
CREATE TABLE bookstore_management.authorities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

--liquibase formatted sql
--changeset chern:2025-03-22-users
CREATE TABLE bookstore_management.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(255) NOT NULL UNIQUE,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    middle_name VARCHAR(255),
    birthday DATE,
    email VARCHAR(255),
    password VARCHAR(255) NOT NULL
);

--liquibase formatted sql
--changeset chern:2025-03-22--users-authorities
CREATE TABLE bookstore_management.users_authorities (
    user_id BIGINT NOT NULL,
    authority_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, authority_id),
    FOREIGN KEY (user_id) REFERENCES bookstore_management.users(id) ON DELETE CASCADE,   -- Added schema name
    FOREIGN KEY (authority_id) REFERENCES bookstore_management.authorities(id) ON DELETE CASCADE -- Added schema name
);
