services:
  bookstore-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "9090:9090"
      - "9091:9091"
    environment:
      - BOOKSTORE_DB_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - BOOKSTORE_DB_USERNAME=${POSTGRES_USER}
      - BOOKSTORE_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KEYCLOAK_BASE_URL=http://keycloak:8080
    networks:
      - bookstore-network

  postgres:
    image: postgres:17.1-alpine3.20
    restart: always
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - bookstore-network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.1.4
    restart: always
    ports:
      - "8443:8443"
      - "58080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_DB_URL: jdbc:postgresql://keycloak_postgres:5432/keycloak
      KC_DB: postgres
      KC_DB_USERNAME: ${KC_POSTGRES_USER}
      KC_DB_PASSWORD: ${KC_POSTGRES_PASSWORD}
    depends_on:
      - keycloak_postgres
    command:
      - "start-dev"
      - "--import-realm"
      - "-features=scripts"
    volumes:
      - ./_keycloak/import/bookstore-realm.json:/opt/keycloak/data/import/bookstore-realm.json
    labels:
      org.springframework.boot.readiness-check.tcp.disable: true
    networks:
      - keycloak-network
      - bookstore-network

  keycloak_postgres:
    container_name: keycloak_postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KC_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KC_POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432
    labels:
      org.springframework.boot.ignore: true
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

networks:
  keycloak-network:
  bookstore-network:

volumes:
  postgres_data:
