name: Build

on: [push]

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Check Docker version
        run: |
          docker --version

      - name: Install Docker Compose V2
        run: |
          DOCKER_COMPOSE_VERSION="v2.27.1"  # replace with the latest version if needed
          sudo mkdir -p /usr/local/lib/docker/cli-plugins
          sudo curl -SL "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-Linux-x86_64" -o /usr/local/lib/docker/cli-plugins/docker-compose
          sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose

      - name: Check if Docker Compose is installed
        run: |
          docker compose version

      - name: Run Docker Compose
        run: |
          docker compose -f docker-compose.yaml up -d

      - name: Build and verify application
        run: |
          mvn verify --no-transfer-progress -DskipTests

      - name: Run Tests
        run: |
          mvn test --no-transfer-progress

      - name: Tear down Docker Compose
        if: always()  # Ensure this runs even if previous steps fail
        run: |
          docker compose -f docker-compose.yaml down
